### PR TITLE
API requests: handle errors

### PR DESCRIPTION
**Pull request by movstox**
@Jellyfishboy I've noticed api returns 'too many requests' error from time to time and this is a proposed way to handle it.

https://shipstation.docs.apiary.io/#introduction/shipstation-api-requirements/api-rate-limits

### CODE REVIEW

**Comment by Jellyfishboy** [comment]
Thanks for your contribution @movstox. Can you resolve the conflicts too please?

**Comment by movstox** [comment]
@Jellyfishboy sure, just noticed and resolved!

**Comment by movstox** [comment]
@Jellyfishboy looks better?

**Comment by Jellyfishboy** [comment]
Awesome thanks @movstox! 👍

**Comment by Jellyfishboy** [comment]
Pushed to rubygems.org: https://rubygems.org/gems/shipstation/versions/0.16.6

**Pull request merged**
